version: '3'
services:
  web:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - cassandra
    command: cassandra:9042
  cassandra:
    image: "cassandra:latest"
    ports:
      - "7001:7000"
      - "7200:7199"
    environment:
      - CASSANDRA_BROADCAST_ADDRESS="127.0.0.1"
      - CASSANDRA_SEEDS="127.0.0.1:7000"